[Hub.Group]
uid = 290

    [[Hub.Group.Node]]
    bus_index = 2
    firmware_version = 'v2.4.1'
    hardware_version = 'TIA_REV2'
    node_id = 17
    revision_id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 3'
        group_location_index = 3
        id = 0

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 4'
        group_location_index = 4
        id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 1'
        group_location_index = 1
        id = 4

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 2'
        group_location_index = 2
        id = 6

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_735nm'
        group_location_index = 1
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_850nm'
        group_location_index = 1
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_735nm'
        group_location_index = 3
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_850nm'
        group_location_index = 3
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_735nm'
        group_location_index = 2
        id = 5

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_850nm'
        group_location_index = 2
        id = 5

    [[Hub.Group.Node]]
    bus_index = 2
    firmware_version = 'v2.4.1'
    hardware_version = 'TIA_REV2'
    node_id = 20
    revision_id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 3'
        group_location_index = 7
        id = 0

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 4'
        group_location_index = 8
        id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 1'
        group_location_index = 5
        id = 4

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 2'
        group_location_index = 6
        id = 6

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_735nm'
        group_location_index = 4
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_850nm'
        group_location_index = 4
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_735nm'
        group_location_index = 6
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_850nm'
        group_location_index = 6
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_735nm'
        group_location_index = 5
        id = 5

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_850nm'
        group_location_index = 5
        id = 5

    [[Hub.Group.Node]]
    bus_index = 2
    firmware_version = 'v2.4.1'
    hardware_version = 'TIA_REV2'
    node_id = 21
    revision_id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 3'
        group_location_index = 11
        id = 0

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 4'
        group_location_index = 12
        id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 1'
        group_location_index = 9
        id = 4

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 2'
        group_location_index = 10
        id = 6

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_735nm'
        group_location_index = 7
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_850nm'
        group_location_index = 7
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_735nm'
        group_location_index = 9
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_850nm'
        group_location_index = 9
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_735nm'
        group_location_index = 8
        id = 5

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_850nm'
        group_location_index = 8
        id = 5

    [[Hub.Group.Node]]
    bus_index = 2
    firmware_version = 'v2.4.1'
    hardware_version = 'TIA_REV2'
    node_id = 22
    revision_id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 3'
        group_location_index = 15
        id = 0

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 4'
        group_location_index = 16
        id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 1'
        group_location_index = 13
        id = 4

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 2'
        group_location_index = 14
        id = 6

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_735nm'
        group_location_index = 10
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_850nm'
        group_location_index = 10
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_735nm'
        group_location_index = 12
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_850nm'
        group_location_index = 12
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_735nm'
        group_location_index = 11
        id = 5

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_850nm'
        group_location_index = 11
        id = 5

    [[Hub.Group.Node]]
    bus_index = 2
    firmware_version = 'v2.4.1'
    hardware_version = 'TIA_REV2'
    node_id = 23
    revision_id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 3'
        group_location_index = 19
        id = 0

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 4'
        group_location_index = 20
        id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 1'
        group_location_index = 17
        id = 4

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 2'
        group_location_index = 18
        id = 6

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_735nm'
        group_location_index = 13
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_850nm'
        group_location_index = 13
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_735nm'
        group_location_index = 15
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_850nm'
        group_location_index = 15
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_735nm'
        group_location_index = 14
        id = 5

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_850nm'
        group_location_index = 14
        id = 5

    [[Hub.Group.Node]]
    bus_index = 2
    firmware_version = 'v2.4.1'
    hardware_version = 'TIA_REV2'
    node_id = 27
    revision_id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 3'
        group_location_index = 23
        id = 0

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 4'
        group_location_index = 24
        id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 1'
        group_location_index = 21
        id = 4

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 2'
        group_location_index = 22
        id = 6

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_735nm'
        group_location_index = 16
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_850nm'
        group_location_index = 16
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_735nm'
        group_location_index = 18
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_850nm'
        group_location_index = 18
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_735nm'
        group_location_index = 17
        id = 5

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_850nm'
        group_location_index = 17
        id = 5

    [[Hub.Group.Node]]
    bus_index = 2
    firmware_version = 'v2.4.1'
    hardware_version = 'TIA_REV2'
    node_id = 28
    revision_id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 3'
        group_location_index = 27
        id = 0

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 4'
        group_location_index = 28
        id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 1'
        group_location_index = 25
        id = 4

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 2'
        group_location_index = 26
        id = 6

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_735nm'
        group_location_index = 19
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_850nm'
        group_location_index = 19
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_735nm'
        group_location_index = 21
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_850nm'
        group_location_index = 21
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_735nm'
        group_location_index = 20
        id = 5

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_850nm'
        group_location_index = 20
        id = 5

    [[Hub.Group.Node]]
    bus_index = 2
    firmware_version = 'v2.4.1'
    hardware_version = 'TIA_REV2'
    node_id = 29
    revision_id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 3'
        group_location_index = 31
        id = 0

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 4'
        group_location_index = 32
        id = 2

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 1'
        group_location_index = 29
        id = 4

        [[Hub.Group.Node.Detector]]
        description = 'ADC Detector Channel 2'
        group_location_index = 30
        id = 6

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_735nm'
        group_location_index = 22
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCA_850nm'
        group_location_index = 22
        id = 1

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_735nm'
        group_location_index = 24
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCC_850nm'
        group_location_index = 24
        id = 3

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_735nm'
        group_location_index = 23
        id = 5

        [[Hub.Group.Node.Source]]
        Source_power = 95.0
        description = 'SRCB_850nm'
        group_location_index = 23
        id = 5